__author__ = 'vinh.vo@sentifi.com'

APP_KEY = "egYRKgKOkJ2Utf06tYUFw"
APP_SECRET = "ezfzK9ddmwCCgBVJKCKHROYfEwX86wWYqLoVMZhicU"
ACCESS_TOKEN = "AAAAAAAAAAAAAAAAAAAAAJE%2FTwAAAAAAne%2BCdSVYVqYFvC7N4J5yFJ% \
                2BtEa8%3DdJ5fRoSbgoIiEPxyrLbMNBaGyEuCnYPp6rRnBRzNk9muo96APl"




