FIELD_TWITTER_DESCRIPTION_ID = '1'
FIELD_TWITTER_SCREEN_NAME_ID = '2'
FIELD_TWITTER_FULL_NAME_ID = '3'

FIELDS = {1: 'TWITTER DESCRIPTION', 2: 'TWITTER_SCREEN_NAME', 3: 'TWITTER_FULL_NAME'}

TWITTER_DESCRIPTION = '1'
TWITTER_SCREEN_NAME = '2'
TWITTER_FULL_NAME = '3'

PHASE_VALUES = ['PROFILE TYPE', 'PUBLISHER GROUP', 'CATEGORY 1', 'CATEGORY 2']
#PHASE_VALUES = ['CATEGORY 1', 'CATEGORY 2', 'PROFILE TYPE', 'PUBLISHER GROUP']

SERVER_STATUS_OK = 'OK'
SERVER_STATUS_ERROR = "ERROR"
